//! The TypeScript declarations, generated from the same types the JSON Schema is.
//!
//! One file, one command, one source of truth. The Action imports these types; it does
//! not hand-write a second copy of the envelope, because a hand-written copy is how the
//! Action and the CLI came to disagree about the shape of a result in the first place.
//!
//! Deterministic by construction: the declaration list is a literal array, `decl()`
//! depends only on the type, and the file is written with the same line endings on
//! every platform. That is what lets `cargo xtask automation check` be a diff.

use crate::result::{
    Application, ArtifactInspectDetails, AutomationResult, BuildDetails, CheckDetails, Composition,
    Details, DoctorCheck, DoctorDetails, DoctorTarget, InspectedContent, InspectedTrust,
    InspectedVariant, PlanDetails, PublishDetails, PublishFailure, PublishStageDetails,
    SignPrepareDetails, SignSubject, SignVerifyDetails, StagedPackage, Status, Target,
    ToolchainCleanDetails, ToolchainComponentStatus, ToolchainInstallDetails,
    ToolchainStatusDetails,
};
use crate::{
    Artifact, ByteCount, Diagnostic, DiagnosticSource, Digest, Identifier, LogLevel,
    ProtocolVersion, Publication, PublicationAsset, Severity, SigningEvidence, SigningState,
    StreamEvent, StreamVersion,
};
use ts_rs::{Config, TS};

/// Every type the Action is allowed to name, in dependency order.
///
/// A literal list rather than a walk of `TS::dependencies`, because the list is the
/// thing a reviewer reads: adding a field to a type is invisible, adding a *type* to the
/// protocol is a line here, and that is the change worth noticing.
/// One type's declaration: the name it is published under, and `ts-rs`'s own
/// renderer for it.
type Declaration = (&'static str, fn(&Config) -> String);

const TYPES: &[Declaration] = &[
    ("ProtocolVersion", ProtocolVersion::decl),
    ("Identifier", Identifier::decl),
    ("Status", Status::decl),
    ("Severity", Severity::decl),
    ("LogLevel", LogLevel::decl),
    ("ByteCount", ByteCount::decl),
    ("Digest", Digest::decl),
    ("SigningEvidence", SigningEvidence::decl),
    ("SigningState", SigningState::decl),
    ("Artifact", Artifact::decl),
    ("Target", Target::decl),
    ("Application", Application::decl),
    ("PublicationAsset", PublicationAsset::decl),
    ("Publication", Publication::decl),
    ("DiagnosticSource", DiagnosticSource::decl),
    ("Diagnostic", Diagnostic::decl),
    ("BuildDetails", BuildDetails::decl),
    ("CheckDetails", CheckDetails::decl),
    ("Composition", Composition::decl),
    ("PlanDetails", PlanDetails::decl),
    ("DoctorCheck", DoctorCheck::decl),
    ("DoctorTarget", DoctorTarget::decl),
    ("DoctorDetails", DoctorDetails::decl),
    ("StagedPackage", StagedPackage::decl),
    ("PublishStageDetails", PublishStageDetails::decl),
    ("PublishFailure", PublishFailure::decl),
    ("PublishDetails", PublishDetails::decl),
    ("SignSubject", SignSubject::decl),
    ("SignPrepareDetails", SignPrepareDetails::decl),
    ("SignVerifyDetails", SignVerifyDetails::decl),
    ("ToolchainInstallDetails", ToolchainInstallDetails::decl),
    ("ToolchainComponentStatus", ToolchainComponentStatus::decl),
    ("ToolchainStatusDetails", ToolchainStatusDetails::decl),
    ("ToolchainCleanDetails", ToolchainCleanDetails::decl),
    ("InspectedVariant", InspectedVariant::decl),
    ("InspectedContent", InspectedContent::decl),
    ("InspectedTrust", InspectedTrust::decl),
    ("ArtifactInspectDetails", ArtifactInspectDetails::decl),
    ("Details", Details::decl),
    ("StreamVersion", StreamVersion::decl),
    ("AutomationResult", AutomationResult::decl),
    ("StreamEvent", StreamEvent::decl),
];

/// The generated TypeScript source, with a header saying where it came from.
pub fn typescript() -> String {
    let config = Config::default();
    let mut out = String::new();
    out.push_str(HEADER);
    for (name, declare) in TYPES {
        let declaration = declare(&config);
        let header = format!("type {name}");
        assert!(
            declaration.starts_with(&header),
            "`{name}` did not declare itself as `{header}`"
        );
        out.push('\n');
        out.push_str("export ");
        out.push_str(declaration.trim_end());
        out.push('\n');
    }
    out
}

/// The header every reader of the file needs before the first line of it.
///
/// A generated file with no provenance is a file somebody will hand-edit, and the next
/// `cargo xtask automation generate` will silently delete the edit.
const HEADER: &str = "\
// Generated by `cargo xtask automation generate`. Do not edit.
//
// The zup automation protocol, as TypeScript. Every type below is derived from the
// Rust DTOs in `crates/zup-automation`; the JSON Schema beside this file in
// `schema/automation-v1.schema.json` is derived from the same types, and is the
// contract for a consumer that is not written in TypeScript.
//
// A consumer accepts any document whose `protocol` shares its major version, and
// ignores fields, event types, operation names, artifact kinds and diagnostic codes it
// does not know. A different major is refused. Nothing here is closed: a field may
// appear that is not declared.
//
// The decoder that reads a document into these types is `src/protocol.ts`, and it is
// hand-written on purpose - it is where the ignore-what-you-do-not-know rule lives.

";
