[package]
name = "zup-linux"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Linux backend for zup"
publish = false

[dependencies]
rustix.workspace = true
semver.workspace = true
serde_json.workspace = true
thiserror.workspace = true
typed-path.workspace = true
uuid.workspace = true
xdg.workspace = true
zup-artifact.workspace = true
zup-binary.workspace = true
zup-bundle.workspace = true
zup-core.workspace = true
zup-exec.workspace = true
zup-plan.workspace = true
zup-platform.workspace = true
zup-transaction.workspace = true

[dev-dependencies]
rstest.workspace = true
semver.workspace = true
tempfile.workspace = true