#![deny(unsafe_code)]

//! Author a native GPUI installer preset for zup.
//!
//! A preset is an ordinary GPUI application that happens to talk to a Zup
//! installer. It draws what the host publishes and asks for what a person
//! clicked, and everything Zup hands it is a session, its settings, and its
//! assets.
//!
//! ```no_run
//! use zup_preset_sdk::prelude::*;
//!
//! #[zup_preset_sdk::Settings]
//! struct Settings {
//!     hero: Option<String>,
//! }
//!
//! struct Aurora;
//!
//! impl Preset for Aurora {
//!     type Settings = Settings;
//!
//!     fn launch(context: PresetContext<Self::Settings>, cx: &mut App) {
//!         // Ordinary GPUI, with the installer's state already published.
//!     }
//! }
//!
//! fn main() {
//!     zup_preset_sdk::run::<Aurora>();
//! }
//! ```
//!
//! # What this crate is not
//!
//! It is not a UI framework. There is no layout abstraction, no screen
//! abstraction, no widget vocabulary, and no preset markup language, because a
//! preset author has [`gpui_kit`] and GPUI itself, and any layout one of those
//! could express the other could too. Everything a preset is given here is
//! Zup-facing: the state the installer is in, the configuration the application
//! chose, and the files it provided.
//!
//! # What a preset can reach
//!
//! Two things: [`Session::send`], which asks the host to do something, and
//! whatever the host publishes. A preset has no access to a plan, a
//! transaction, an elevation decision, or a package, and asking for one is not
//! an omission - it is the boundary that makes a third-party preset safe to
//! ship. The host validates every action against the state it owns, so a preset
//! that asks for something this installation cannot do is refused rather than
//! obeyed.
//!
//! # GPUI versions
//!
//! A preset project depends on this crate alone. [`gpui_kit`] is re-exported,
//! so the GPUI stack a preset builds against is the one this SDK was built
//! against and there is nothing to keep in step.

mod asset;
mod preset;
mod session;
mod settings;
mod transport;

pub mod prelude;

pub use asset::{ApplicationAssets, AssetRef, PresetAssets};
pub use preset::{
    Describe, NoSettings, Preset, PresetContext, PresetError, Settings, describe, run, serve,
};
pub use session::{ActionSender, Session, SessionState};
pub use settings::PresetSettings;

// The transport is not re-exported. `Bootstrap` and `TransportError` appear in
// `serve`'s signature because a preset that has already been handed a bootstrap
// - which nothing a preset author has, since a preset is launched by a host -
// needs a way to hand it on. Everything else in `transport` is the handshake's
// own machinery: a preset reaches the host through `Session::send` and sees the
// host's state through `SessionState`, and nothing in between is something an
// author has any reason to name.

/// A preset's typed settings, with the derives Zup needs already applied.
///
/// An attribute rather than a derive because a derive is appended to what it
/// annotates and cannot add another derive to it. Applying it here rather than
/// in a preset's manifest is what keeps `serde` and `schemars` out of a preset's
/// dependencies: the schema that validates an application's settings is
/// generated by the same `schemars` the preset deserializes with.
pub use zup_preset_sdk_macros::settings;

/// The host's own vocabulary.
///
/// A preset that renders what the host is *doing* - a diagnostic, a plan
/// preview, a maintenance surface - names these. A preset that only presents
/// what a person chose reaches [`prelude`] instead, which is the narrower set.
pub use zup_preset_protocol as host;

/// The GPUI stack a preset is written against.
///
/// Re-exported rather than depended on directly: a preset project lists this
/// crate and nothing else, so upgrading the GPUI stack is one version bump
/// rather than a sweep through four crates.
pub use gpui_kit;

/// The crates a preset's settings are built from, re-exported so the macro
/// applied by [`settings`] resolves them.
///
/// Hidden because it is not an authoring surface: a preset applies the
/// attribute and never names these. Exposed under one path from here and from
/// the facade above, because the macro resolves them through `zup_sdk` and a
/// preset should not have to know which of the two it depends on.
#[doc(hidden)]
pub mod __private {
    pub use schemars;
    pub use serde;
    pub use serde_json;
}

// The path the `#[settings]` attribute resolves its derives through. The crate
// is given the name an author depends on, so the same macro works unchanged
// whether a preset reached it through `zup-sdk` or through the crate beneath -
// one spelling reaches one set of versions whichever way the author got here.
pub extern crate self as zup_sdk;
