[package]
name = "zup-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Runtime orchestration layer for zup"

[dependencies]
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-appender = "0.2"
semver.workspace = true
thiserror.workspace = true
tokio = { version = "1", features = [
  "rt-multi-thread",
  "macros",
  "net",
  "io-util",
  "sync",
  "time",
  "process",
] }
tokio-util = { version = "0.7", features = ["codec"] }
uuid.workspace = true
zup-bootstrap.workspace = true
zup-bundle.workspace = true
zup-core.workspace = true
zup-protocol.workspace = true
zup-transaction.workspace = true
