// Generated by `cargo xtask automation generate`. Do not edit.
//
// The zup automation protocol, as TypeScript. Every type below is derived from the
// Rust DTOs in `crates/zup-automation`; the JSON Schema beside this file in
// `schema/automation-v1.schema.json` is derived from the same types, and is the
// contract for a consumer that is not written in TypeScript.
//
// A consumer accepts any document whose `protocol` shares its major version, and
// ignores fields, event types, operation names, artifact kinds and diagnostic codes it
// does not know. A different major is refused. Nothing here is closed: a field may
// appear that is not declared.
//
// The decoder that reads a document into these types is `src/protocol.ts`, and it is
// hand-written on purpose - it is where the ignore-what-you-do-not-know rule lives.


export type ProtocolVersion = string;

export type Identifier = string;

export type Status = "success" | "failure";

export type Severity = "error" | "warning" | "notice";

export type LogLevel = "info" | "warning" | "error";

export type ByteCount = number;

export type Digest = { 
/**
 * The digest algorithm, lowercased. `sha256` is the only one zup emits today.
 */
algorithm: string, 
/**
 * The digest, lowercase hex.
 */
value: string, };

export type SigningEvidence = { fact: string, value: string, };

export type SigningState = { 
/**
 * `unsigned`, `signed`, or `unverified` when a signature exists but has not been
 * accepted against a policy.
 */
state: Identifier, 
/**
 * The facts the platform established, in the order it established them.
 */
evidence: Array<SigningEvidence>, };

export type Artifact = { 
/**
 * Release-relative, `/`-separated. Never a build-machine absolute path.
 */
path: string, 
/**
 * The digest of the bytes as they stand now.
 */
digest: Digest, 
/**
 * The size of those bytes.
 */
size: ByteCount, 
/**
 * What the artifact is: `single`, `universal`, `thin`, `package`, `document`.
 */
kind: Identifier, 
/**
 * How it behaves: `offline`, `thin`, `package`.
 */
mode: Identifier, 
/**
 * The declared artifact id, when the manifest named one.
 */
id: string | null, 
/**
 * The target triple, for an artifact that serves exactly one machine.
 */
target: string | null, 
/**
 * The variant ids this artifact carries, for one that serves several.
 */
variants: Array<string> | null, 
/**
 * What is known about its signature, once signing has been attempted.
 *
 * `null` means nobody has looked, which is a different fact from an empty list
 * meaning "looked, and there is no signature". An unsigned release is a real
 * release: it is finalized, it has a published identity, and nothing proves who
 * produced it.
 */
signing: SigningState | null, };

export type Target = { 
/**
 * The profile name from `[build.targets]`.
 */
profile: string, 
/**
 * The canonical target triple the profile resolves to.
 */
target: string, };

export type Application = { 
/**
 * The reverse-DNS identifier, e.g. `com.acme.desktop`.
 */
id: string, 
/**
 * The display name.
 */
name: string, 
/**
 * The version, as the manifest spells it.
 */
version: string, };

export type PublicationAsset = { 
/**
 * The name the release carries it under. Flat, because that is how a host
 * addresses an asset.
 */
name: string, 
/**
 * Its size on the host.
 */
size: ByteCount, 
/**
 * The digest zup published, when it published one.
 */
digest: Digest | null, 
/**
 * `uploaded`, `existing`, `replaced`, or whatever the provider reported.
 */
state: Identifier, };

export type Publication = { 
/**
 * The provider, e.g. `github`.
 */
provider: string, 
/**
 * Where it went, in the provider's own terms: `owner/name`, or
 * `host/owner/name` on an installation that is not the public one.
 */
subject: string, 
/**
 * The tag the release answers to.
 */
tag: string, 
/**
 * The provider's identifier for it, when it has one.
 *
 * A string because whether a provider's id fits in a double is the provider's
 * business. Encoding it as a number is how a release id silently becomes
 * `1.2345678901234568e18` somewhere between the host and a log line.
 */
id: string | null, 
/**
 * `published`, `draft`, `prerelease`, `deleted`, or whatever the provider says.
 */
state: Identifier, 
/**
 * The address a person can open, when there is one.
 */
url: string | null, 
/**
 * Whether the host refuses to replace these bytes. `null` when it did not say.
 */
immutable: boolean | null, 
/**
 * The files the release carries.
 */
assets: Array<PublicationAsset>, 
/**
 * The provider's own receipt, project-relative, when one was written.
 *
 * Named rather than inlined: the receipt is the provider's document in the
 * provider's shape, and a contract that absorbed it would have to version it
 * separately. A machine consumer that wants the tag, the state and the asset
 * names does not need to read it.
 */
receipt: string | null, };

export type DiagnosticSource = { 
/**
 * The file, as the diagnostic names it. Usually project-relative.
 */
file: string, 
/**
 * 1-based.
 */
start_line: number | null, 
/**
 * 1-based.
 */
start_column: number | null, 
/**
 * 1-based, inclusive.
 */
end_line: number | null, 
/**
 * 1-based, inclusive.
 */
end_column: number | null, };

export type Diagnostic = { 
/**
 * How loudly zup is saying it.
 */
severity: Severity, 
/**
 * A stable identifier, e.g. `zup.manifest.unknown_target`.
 */
code: Identifier, 
/**
 * The one-sentence statement of what is wrong.
 */
message: string, 
/**
 * Where it is wrong, when zup knows.
 */
source: DiagnosticSource | null, 
/**
 * The line a developer can act on.
 */
help: string | null, };

export type BuildDetails = { 
/**
 * The signing plan, project-relative, when one was written.
 */
signing_plan: string | null, 
/**
 * How many files the plan says an external signer has to touch.
 */
pending_signatures: number, };

export type CheckDetails = { 
/**
 * How many variant descriptions the selected targets resolved into.
 */
variants: number, 
/**
 * Whether the selected targets can be composed into one artifact, and why not when
 * they cannot. `None` means fewer than two were selected, which is not a finding.
 */
composition: Composition | null, };

export type Composition = { 
/**
 * Whether they can.
 */
composable: boolean, 
/**
 * The dimension that refused, when it did.
 */
dimension: Identifier | null, 
/**
 * The one-line reason, in zup's words.
 */
detail: string, };

export type PlanDetails = { 
/**
 * `user` or `machine`.
 */
scope: string, 
/**
 * Where it would install, when the project chose a directory.
 */
install_directory: string | null, 
/**
 * What it would write.
 */
estimated_bytes: ByteCount, 
/**
 * How many individual changes it holds.
 */
change_count: number, };

export type DoctorCheck = { 
/**
 * The check's kind, e.g. `manifest_compile`.
 */
kind: Identifier, 
/**
 * `pass`, `fail` or `skip`.
 */
status: Identifier, 
/**
 * What it found.
 */
message: string, 
/**
 * The file it examined, when it examined one.
 */
path: string | null, };

export type DoctorTarget = { 
/**
 * The profile name.
 */
profile: string, 
/**
 * The triple it resolves to.
 */
target: string, 
/**
 * `pass`, `fail` or `skip`.
 */
status: Identifier, 
/**
 * Every check that ran, in report order.
 */
checks: Array<DoctorCheck>, };

export type DoctorDetails = { 
/**
 * The manifest it read, project-relative.
 */
manifest: string, 
/**
 * The build host's canonical target triple.
 */
host: string, 
/**
 * Whether every selected target is ready to build.
 */
ready: boolean, 
/**
 * How many checks ran.
 */
checks: number, 
/**
 * Per-profile verdicts and the checks underneath each.
 */
targets: Array<DoctorTarget>, };

export type StagedPackage = { 
/**
 * The variant it carries.
 */
variant: string, 
/**
 * The files, by flat asset name. Several when a package was sharded.
 */
names: Array<string>, 
/**
 * How big they are together.
 */
size: ByteCount, 
/**
 * How many content objects went in.
 */
blob_count: number, };

export type PublishStageDetails = { 
/**
 * The staged web tree, project-relative.
 */
web_root: string, 
/**
 * The channel the tree answers to.
 */
channel: string, 
/**
 * How many distinct content objects the tree carries.
 */
objects: number, 
/**
 * How big they are together.
 */
object_bytes: ByteCount, 
/**
 * How many variants the release describes.
 */
variants: number, 
/**
 * How many documents `tuftool` is meant to sign.
 */
tuf_inputs: number, 
/**
 * The digest of the release descriptor, so a consumer can prove which release the
 * tree is without reading it.
 */
release_digest: string | null, 
/**
 * One transport package per variant, when `--packages` was asked for.
 */
packages: Array<StagedPackage>, 
/**
 * The two thin installers, when `--thin` was asked for.
 */
thin_installers: Array<Artifact>, 
/**
 * The release description folded from a build matrix, when `--release-dir` was
 * given.
 */
release_manifest: string | null, };

export type PublishFailure = { 
/**
 * The provider's phase name.
 */
phase: string, 
/**
 * The file or check it was on.
 */
step: string, 
/**
 * Why.
 */
detail: string, };

export type PublishDetails = { 
/**
 * Whether nothing was written.
 */
dry_run: boolean, 
/**
 * Where the provider's receipt went, project-relative.
 */
receipt: string | null, 
/**
 * The steps that failed, which is what a failed publication needs and what a
 * successful one does not.
 */
failures: Array<PublishFailure>, };

export type SignSubject = { 
/**
 * Release-relative path, `/`-separated.
 */
path: string, 
/**
 * `native_runtime` or `outer_artifact`.
 */
role: Identifier, 
/**
 * `pre_compose` or `post_compose`.
 */
stage: Identifier, 
/**
 * The variants it belongs to.
 */
variants: Array<string>, 
/**
 * Whether the check passed. `false` is a report, not a refusal: `--report-only`
 * exists so a pipeline can see every failure before it decides to stop.
 */
verified: boolean, 
/**
 * What was established, in one line.
 */
detail: string, 
/**
 * The digest measured from the bytes on disk, when they could be read.
 */
digest: Digest | null, 
/**
 * The size of those bytes.
 */
size: ByteCount | null, };

export type SignPrepareDetails = { 
/**
 * The plan that was written, project-relative.
 */
plan: string, 
/**
 * The subjects, in signing order. Order is the plan's: a runtime is signed before
 * the artifact that embeds it.
 */
subjects: Array<SignSubject>, };

export type SignVerifyDetails = { 
/**
 * The plan that was read, project-relative.
 */
plan: string, 
/**
 * Every subject, verified or not.
 */
subjects: Array<SignSubject>, 
/**
 * How many artifacts now carry a finalized published identity.
 */
finalized: number, 
/**
 * How many are finalized but carry no signature.
 */
unsigned: number, };

export type ToolchainInstallDetails = { 
/**
 * The zup release the bytes came from.
 */
zup_version: string, 
/**
 * The directory they were read from.
 */
source: string, 
/**
 * The directory they now live in.
 */
cache: string, 
/**
 * The component file names, sorted.
 */
components: Array<string>, };

export type ToolchainComponentStatus = { 
/**
 * The component, in the wording every refusal uses.
 */
component: string, 
/**
 * Whether a usable copy was found.
 */
found: boolean, 
/**
 * Which arm of the search produced it: `override`, `root`, `cache` or `staged`.
 */
source: Identifier | null, 
/**
 * The file, when one was found.
 */
path: string | null, 
/**
 * Why it was refused, when it was.
 */
problem: string | null, };

export type ToolchainStatusDetails = { 
/**
 * The zup release these components have to come from.
 */
zup_version: string, 
/**
 * The build host's canonical target triple.
 */
host: string, 
/**
 * Where this version's cache lives on this machine.
 *
 * Absolute, and the one path in this contract that is: it answers "where would a
 * build here look", which is the question this operation exists to answer, and
 * nothing reads it back. It is for display and for matching against a machine's
 * own state - never a release identity.
 */
cache: string, 
/**
 * Whether every component a build needs is usable.
 */
complete: boolean, 
/**
 * One entry per component, in the order a build asks for them.
 */
components: Array<ToolchainComponentStatus>, };

export type ToolchainCleanDetails = { 
/**
 * The directory that was cleaned.
 */
cache: string, 
/**
 * True when nothing was changed.
 */
dry_run: boolean, 
/**
 * One entry per removed version or file.
 */
removed: Array<string>, 
/**
 * The versions that were left alone.
 */
kept: Array<string>, };

export type InspectedVariant = { id: string, target: string, frontend: string, 
/**
 * The size this variant's content is worth, counting shared bytes.
 */
logical_size: ByteCount, file_count: number, prerequisite_count: number, plugin_count: number, 
/**
 * Whether the variant refuses to run under a compatibility layer.
 */
native_execution: boolean, 
/**
 * Whether the runtime image this variant carries is built for the target the
 * index names.
 *
 * The index's `target` is a claim; the runtime's own header is an independent
 * statement, and this is the comparison between them.
 */
target_matches_binary: string, };

export type InspectedContent = { 
/**
 * Every variant's content, counted once per variant.
 */
logical_size: ByteCount, 
/**
 * The distinct content the artifact actually stores.
 */
stored_size: ByteCount, 
/**
 * The distinct content before compression.
 */
content_size: ByteCount, 
/**
 * Bytes more than one variant needs.
 */
shared_size: ByteCount, 
/**
 * Bytes only one variant needs.
 */
exclusive_size: ByteCount, unique_blob_count: number, 
/**
 * Bytes the file on disk occupies.
 */
file_size: ByteCount, };

export type InspectedTrust = { 
/**
 * Whether the image carries a signature structure whose digest covers these bytes.
 */
authenticode: string, 
/**
 * Whether the index parses and agrees with the content beside it.
 */
index: string, 
/**
 * Whether every advertised content digest verifies, `named` when the artifact
 * carries none to verify.
 */
content_digests: string, 
/**
 * Whether every variant the index names is complete.
 */
variants: string, };

export type ArtifactInspectDetails = { 
/**
 * The file that was inspected, as it was named on the command line.
 */
artifact: string, 
/**
 * `single`, `universal` or `thin`.
 */
artifact_kind: Identifier, 
/**
 * `offline` or `online`.
 */
artifact_mode: Identifier, 
/**
 * Whether the artifact always installs one version or follows a channel.
 */
pin: string, 
/**
 * The launcher experience it presents.
 */
subsystem: string, 
/**
 * One entry per variant it carries.
 */
variants: Array<InspectedVariant>, 
/**
 * What the artifact costs, and what composing it saved.
 */
content: InspectedContent, 
/**
 * What can be proven about its trust, one field per question.
 */
trust: InspectedTrust, };

export type Details = { "kind": "build" } & BuildDetails | { "kind": "check" } & CheckDetails | { "kind": "plan" } & PlanDetails | { "kind": "doctor" } & DoctorDetails | { "kind": "publish.stage" } & PublishStageDetails | { "kind": "publish.github" } & PublishDetails | { "kind": "sign.prepare" } & SignPrepareDetails | { "kind": "sign.verify" } & SignVerifyDetails | { "kind": "toolchain.install" } & ToolchainInstallDetails | { "kind": "toolchain.status" } & ToolchainStatusDetails | { "kind": "toolchain.clean" } & ToolchainCleanDetails | { "kind": "artifact.inspect" } & ArtifactInspectDetails;

export type StreamVersion = { 
/**
 * The contract this stream is written to.
 */
protocol: ProtocolVersion, 
/**
 * The zup release producing it.
 */
zup: string, 
/**
 * The operation that is about to run.
 */
operation: Identifier, };

export type AutomationResult = { 
/**
 * The contract this document is written to.
 */
protocol: ProtocolVersion, 
/**
 * The operation that ran, in zup's own vocabulary.
 */
operation: Identifier, 
/**
 * Whether it did what it was asked.
 */
status: Status, 
/**
 * The application, when the command read a manifest.
 */
application: Application | null, 
/**
 * The targets the operation selected.
 */
targets: Array<Target>, 
/**
 * The files the operation produced.
 */
artifacts: Array<Artifact>, 
/**
 * The release description, project-relative, when one was written.
 */
release_manifest: string | null, 
/**
 * Where a release went, when one was published.
 */
publication: Publication | null, 
/**
 * Everything zup wants the reader to know. Present on success too.
 */
diagnostics: Array<Diagnostic>, 
/**
 * One line a human would have read. Never parsed.
 */
summary: string | null, 
/**
 * The operation's own result, beyond what every integration needs.
 */
details: Details | null, };

export type StreamEvent = { "type": "version" } & StreamVersion | { "type": "phase", 
/**
 * A short, stable name for the step.
 */
phase: string, 
/**
 * The sentence a person would have read.
 */
message: string, } | { "type": "progress", 
/**
 * Items finished.
 */
completed: number, 
/**
 * Items in total. Always greater than zero: a progress event with no total has
 * nothing to be a fraction of, and a consumer that rendered it would be
 * showing a number that means nothing.
 */
total: number, 
/**
 * The label a person would have read.
 */
label: string, } | { "type": "diagnostic", diagnostic: Diagnostic, } | { "type": "artifact", artifact: Artifact, } | { "type": "publication", publication: Publication, } | { "type": "log", level: LogLevel, message: string, } | { "type": "completed", result: AutomationResult, };
