[package]
name = "zup-pe"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Portable Executable resources and headers for zup"

[dependencies]
thiserror.workspace = true
windows-link.workspace = true

[dev-dependencies]
tempfile.workspace = true
