[package]
name = "zup-sdk"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/orielhaim/zup"
description = "Author a Zup installer preset or an installation plugin"
publish = true

[features]
preset = ["dep:zup-preset-sdk"]
plugin = ["dep:zup-plugin-sdk"]

test-support = ["zup-preset-sdk?/test-support"]

[dependencies]
zup-plugin-sdk = { path = "../zup-plugin-sdk", version = "0.1.0", optional = true }
zup-preset-sdk = { path = "../zup-preset-sdk", version = "0.1.0", optional = true }

[package.metadata.docs.rs]
all-features = true
