use std::collections::BTreeMap;
use std::fmt::Write as _;

use crate::pins::{PinError, pin};
use crate::runner::{Runner, cross_runner, native_runner};

pub const DEFAULT_ACTION: &str = "orielhaim/zup@action-v1";

pub const WORKFLOW_PATH: &str = ".github/workflows/release.yml";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MatrixTarget {
    pub profile: String,
    pub triple: String,
}

impl MatrixTarget {
    pub fn new(profile: impl Into<String>, triple: impl Into<String>) -> Self {
        Self {
            profile: profile.into(),
            triple: triple.into(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Signing {
    pub command: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WorkflowPolicy {
    pub name: String,
    pub tag_glob: String,
    pub environment: Option<String>,
    pub attestations: bool,
    pub attest_paths: Vec<String>,
    pub signing: Option<Signing>,
    pub compose_runner: String,
    pub runner_overrides: BTreeMap<String, String>,
    pub release_dir: String,
    pub receipt: String,
    pub action: String,
}

impl Default for WorkflowPolicy {
    fn default() -> Self {
        Self {
            name: "release".to_owned(),
            tag_glob: "v*".to_owned(),
            environment: None,
            attestations: true,
            attest_paths: Vec::new(),
            signing: None,
            compose_runner: "windows-latest".to_owned(),
            runner_overrides: BTreeMap::new(),
            release_dir: "dist".to_owned(),
            receipt: "dist/github-publish.json".to_owned(),
            action: DEFAULT_ACTION.to_owned(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Freshness {
    pub current: bool,
    pub path: String,
    pub present: bool,
    pub detail: String,
}

const GENERATED_HEADER: &str = "\
# Generated by `zup ci github generate`. Edit `zup.toml`, not this file.
# `zup ci github check` fails when the two disagree.
";

fn uses(repository: &str) -> String {
    match pin(repository) {
        Ok(action) => action.uses(),
        Err(PinError::Unknown { .. }) => {
            panic!("{repository} is not in the action pin lock; see github-actions.lock.json")
        }
    }
}

pub fn generate(policy: &WorkflowPolicy, targets: &[MatrixTarget]) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    let _ = writeln!(out, "name: {}", policy.name);
    out.push('\n');
    out.push_str("on:\n");
    let _ = writeln!(out, "  push:\n    tags: [\"{}\"]", policy.tag_glob);
    out.push_str("  workflow_dispatch:\n");
    out.push_str("    inputs:\n");
    out.push_str(
        "      tag:\n        description: \"release tag to publish\"\n        required: true\n",
    );
    out.push_str("      dry_run:\n");
    out.push_str("        description: \"plan and verify without publishing\"\n");
    out.push_str("        type: boolean\n        default: false\n");
    out.push('\n');
    out.push_str("# Least privilege at the top, and narrower still per job. A build job\n");
    out.push_str("# cannot write to the repository; only the publish job can.\n");
    out.push_str("permissions:\n  contents: read\n");
    out.push('\n');
    out.push_str("concurrency:\n");
    let _ = writeln!(
        out,
        "  group: release-${{{{ github.repository }}}}-${{{{ github.event.inputs.tag || github.ref_name }}}}"
    );
    out.push_str("  cancel-in-progress: false\n");
    out.push('\n');
    out.push_str("jobs:\n");

    plan(policy, targets, &mut out);
    build(policy, targets, &mut out);
    compose(policy, targets, &mut out);
    sign(policy, &mut out);
    let signed = vec!["compose", "sign"];
    if policy.attestations {
        attest(policy, &signed, &mut out);
    }
    publish(policy, &signed, policy.attestations, &mut out);
    out
}

fn plan(_policy: &WorkflowPolicy, targets: &[MatrixTarget], out: &mut String) {
    out.push_str("  plan:\n");
    out.push_str("    name: plan\n");
    out.push_str("    runs-on: ubuntu-latest\n");
    out.push_str("    permissions:\n      contents: read\n");
    out.push_str("    outputs:\n");
    out.push_str("      profiles: ${{ steps.plan.outputs.profiles }}\n");
    out.push_str("    steps:\n");
    step(
        out,
        "Checkout",
        &uses("actions/checkout"),
        &["fetch-depth: '0'"],
    );
    out.push_str("      - name: Resolve the plan\n        run: |\n");
    out.push_str("          zup ci github check --format json\n");
    let _ = writeln!(
        out,
        "          echo \"profiles={profile_list}\" >> \"$GITHUB_OUTPUT\"",
        profile_list = targets
            .iter()
            .map(|target| target.profile.as_str())
            .collect::<Vec<_>>()
            .join(",")
    );
    out.push('\n');
}

fn build(policy: &WorkflowPolicy, targets: &[MatrixTarget], out: &mut String) {
    out.push_str("  build:\n");
    out.push_str("    name: build ${{ matrix.profile }}\n");
    out.push_str("    needs: plan\n");
    out.push_str("    runs-on: ${{ matrix.runner }}\n");
    out.push_str("    permissions:\n      contents: read\n");
    out.push_str("    strategy:\n      fail-fast: false\n      matrix:\n");
    out.push_str("        include:\n");
    for target in targets {
        let runner = policy
            .runner_overrides
            .get(&target.triple)
            .cloned()
            .unwrap_or_else(|| {
                native_runner(&target.triple)
                    .map(|runner: Runner| runner.label().to_owned())
                    .unwrap_or_else(|| cross_runner(&target.triple).to_owned())
            });
        let _ = writeln!(
            out,
            "          - profile: {}\n            target: {}\n            runner: {runner}",
            target.profile, target.triple
        );
    }
    out.push_str("    steps:\n");
    step(
        out,
        "Checkout",
        &uses("actions/checkout"),
        &["persist-credentials: false"],
    );
    let _ = writeln!(
        out,
        "      - name: Build variant\n        uses: {}\n        with:\n          operation: build\n          target: ${{{{ matrix.profile }}}}\n          release-dir: {release}/variants/${{{{ matrix.profile }}}}\n          upload-workflow-artifacts: true\n          workflow-artifact-name: variant-${{{{ matrix.profile }}}}\n          artifact-retention-days: 7",
        policy.action,
        release = policy.release_dir
    );
    out.push('\n');
}

fn compose(policy: &WorkflowPolicy, targets: &[MatrixTarget], out: &mut String) {
    out.push_str("  compose:\n");
    out.push_str("    name: compose\n");
    out.push_str("    needs: [plan, build]\n");
    let _ = writeln!(out, "    runs-on: {}", policy.compose_runner);
    out.push_str("    permissions:\n      contents: read\n");
    out.push_str("    steps:\n");
    step(
        out,
        "Checkout",
        &uses("actions/checkout"),
        &["persist-credentials: false"],
    );
    let _ = writeln!(
        out,
        "      - name: Collect variants\n        uses: {}\n        with:\n          pattern: variant-*\n          path: {}/variants\n          merge-multiple: true",
        uses("actions/download-artifact"),
        policy.release_dir
    );
    let mut inputs = vec![format!("{}/**", policy.release_dir)];
    for target in targets {
        inputs.push(format!(
            "!{}/variants/{}/{}",
            policy.release_dir,
            target.profile,
            zup_artifact::RELEASE_MANIFEST_NAME
        ));
    }
    let _ = writeln!(
        out,
        "      - name: Compose release\n        uses: {}\n        with:\n          operation: compose\n          release-dir: {}",
        policy.action, policy.release_dir
    );
    out.push_str("      # collected by this job:\n");
    for input in &inputs {
        let _ = writeln!(out, "      #   {input}");
    }
    if policy.signing.is_none() {
        out.push_str(
            "      # No signing command is configured, so this release publishes unsigned\n\
             \x20     # artifacts and Windows SmartScreen will warn about them. Set\n\
             \x20     # `[publish.github.workflow] signing` in zup.toml and regenerate.\n",
        );
        let _ = writeln!(
            out,
            "      - name: Finalize\n        uses: {}\n        with:\n          operation: finalize\n          release-dir: {}\n          allow-unsigned: true",
            policy.action, policy.release_dir
        );
    }
    let _ = writeln!(
        out,
        "      - name: Upload the release\n        uses: {}\n        with:\n          name: {}\n          path: {}\n          retention-days: 7\n          if-no-files-found: error",
        uses("actions/upload-artifact"),
        composed_artifact(policy),
        policy.release_dir
    );
    out.push('\n');
}

fn composed_artifact(policy: &WorkflowPolicy) -> &'static str {
    if policy.signing.is_some() {
        "compose-unsigned"
    } else {
        "compose"
    }
}

fn sign(policy: &WorkflowPolicy, out: &mut String) {
    let Some(signing) = &policy.signing else {
        return;
    };
    out.push_str("  sign:\n");
    out.push_str("    name: sign and finalize\n");
    out.push_str("    needs: compose\n");
    let _ = writeln!(out, "    runs-on: {}", policy.compose_runner);
    out.push_str("    permissions:\n      contents: read\n");
    out.push_str("    steps:\n");
    step(
        out,
        "Checkout",
        &uses("actions/checkout"),
        &["persist-credentials: false"],
    );
    let _ = writeln!(
        out,
        "      - name: Collect the composed release\n        uses: {}\n        with:\n          name: {}\n          path: {}",
        uses("actions/download-artifact"),
        composed_artifact(policy),
        policy.release_dir
    );
    let _ = writeln!(
        out,
        "      - name: Sign\n        shell: pwsh\n        working-directory: {}\n        run: |",
        policy.release_dir
    );
    for line in signing.command.lines() {
        let _ = writeln!(out, "          {line}");
    }
    let _ = writeln!(
        out,
        "      - name: Verify signatures and finalize\n        uses: {}\n        with:\n          operation: finalize\n          release-dir: {}",
        policy.action, policy.release_dir
    );
    let _ = writeln!(
        out,
        "      - name: Upload the signed release\n        uses: {}\n        with:\n          name: compose\n          path: {}\n          retention-days: 7\n          if-no-files-found: error",
        uses("actions/upload-artifact"),
        policy.release_dir
    );
    out.push('\n');
}

fn needs(upstream: &[&str], attestations: bool) -> String {
    let mut list: Vec<String> = upstream.iter().map(|name| (*name).to_owned()).collect();
    if attestations {
        list.push("attest".to_owned());
    }
    format!("[{}]", list.join(", "))
}

fn attest(policy: &WorkflowPolicy, upstream: &[&str], out: &mut String) {
    out.push_str("  attest:\n");
    out.push_str("    name: attest\n");
    let _ = writeln!(out, "    needs: {}", needs(upstream, false));
    out.push_str("    runs-on: ubuntu-latest\n");
    out.push_str("    permissions:\n");
    out.push_str("      contents: read\n");
    out.push_str("      id-token: write\n");
    out.push_str("      attestations: write\n");
    out.push_str("    steps:\n");
    step(
        out,
        "Checkout",
        &uses("actions/checkout"),
        &["persist-credentials: false"],
    );
    let _ = writeln!(
        out,
        "      - name: Collect the finalized release\n        uses: {}\n        with:\n          name: compose\n          path: {}",
        uses("actions/download-artifact"),
        policy.release_dir
    );
    let _ = writeln!(
        out,
        "      - name: Attest provenance\n        uses: {}\n        with:\n          operation: attest\n          release-dir: {}",
        policy.action, policy.release_dir
    );
    if !policy.attest_paths.is_empty() {
        let _ = writeln!(out, "          attest-paths: |");
        for path in &policy.attest_paths {
            let _ = writeln!(out, "            {path}");
        }
    }
    out.push('\n');
}

fn publish(policy: &WorkflowPolicy, upstream: &[&str], attestations: bool, out: &mut String) {
    out.push_str("  publish:\n");
    out.push_str("    name: publish\n");
    let _ = writeln!(out, "    needs: {}", needs(upstream, attestations));
    out.push_str("    runs-on: ubuntu-latest\n");
    out.push_str("    permissions:\n      contents: write\n");
    if let Some(environment) = &policy.environment {
        let _ = writeln!(out, "    environment: {environment}");
    }
    out.push_str("    steps:\n");
    step(
        out,
        "Checkout",
        &uses("actions/checkout"),
        &["persist-credentials: false"],
    );
    let _ = writeln!(
        out,
        "      - name: Collect the finalized release\n        uses: {}\n        with:\n          name: compose\n          path: {}",
        uses("actions/download-artifact"),
        policy.release_dir
    );
    let _ = writeln!(
        out,
        "      - name: Publish release\n        uses: {}\n        with:\n          operation: publish\n          release-dir: {}\n          receipt: {}\n          github-token: ${{{{ secrets.GITHUB_TOKEN }}}}\n          dry-run: ${{{{ github.event.inputs.dry_run == 'true' }}}}",
        policy.action, policy.release_dir, policy.receipt
    );
}

fn step(out: &mut String, name: &str, uses: &str, inputs: &[&str]) {
    let _ = writeln!(out, "      - name: {name}\n        uses: {uses}");
    if inputs.is_empty() {
        return;
    }
    out.push_str("        with:\n");
    for input in inputs {
        let _ = writeln!(out, "          {input}");
    }
}

pub fn check(
    root: &std::path::Path,
    policy: &WorkflowPolicy,
    targets: &[MatrixTarget],
) -> Freshness {
    let expected = generate(policy, targets);
    let path = root.join(WORKFLOW_PATH);
    let present = path.is_file();
    if !present {
        return Freshness {
            current: false,
            present: false,
            path: WORKFLOW_PATH.to_owned(),
            detail: format!("{WORKFLOW_PATH} does not exist; run `zup ci github generate`"),
        };
    }
    let actual = std::fs::read_to_string(&path).unwrap_or_default();
    if actual == expected {
        return Freshness {
            current: true,
            present: true,
            path: WORKFLOW_PATH.to_owned(),
            detail: format!("{WORKFLOW_PATH} matches the generator"),
        };
    }
    Freshness {
        current: false,
        present: true,
        path: WORKFLOW_PATH.to_owned(),
        detail: format!(
            "{WORKFLOW_PATH} no longer matches the generator; run `zup ci github generate` \
             and review the diff"
        ),
    }
}
