[package]
name = "zup"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Developer tool for building and distributing zup installers"
default-run = "zup"

[features]
default = []

[[bin]]
name = "zup"
path = "src/main.rs"

[dependencies]
clap.workspace = true
clap_complete.workspace = true
inquire.workspace = true
miette.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
toml_edit.workspace = true
zup-acquire.workspace = true
zup-artifact.workspace = true
zup-build.workspace = true
zup-core.workspace = true
zup-distribute-github.workspace = true
zup-exec.workspace = true
zup-manifest.workspace = true
zup-pe.workspace = true
zup-plan.workspace = true
zup-plugin-build.workspace = true
zup-plugin-contract.workspace = true
zup-presentation.workspace = true
zup-publish.workspace = true
zup-publish-github.workspace = true
zup-signing.workspace = true
zup-toolchain.workspace = true
zup-windows.workspace = true

[dev-dependencies]
tempfile.workspace = true
zstd.workspace = true
wat = "1"
windows-registry.workspace = true
wit-component = { version = "=0.259.0", features = ["dummy-module"] }
wit-parser = "=0.259.0"
zup-xtask.workspace = true
