[package]
name = "zup-bundle"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Payload and container layer for zup"

[dependencies]
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
zstd.workspace = true
tempfile.workspace = true
zup-core.workspace = true
zup-build.workspace = true

[dev-dependencies]
rstest.workspace = true
zup-manifest.workspace = true
